/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GoalCreateGoalRequest } from '../models';
// @ts-ignore
import type { GoalGoalListResponse } from '../models';
// @ts-ignore
import type { GoalGoalResponse } from '../models';
// @ts-ignore
import type { ResponseErrorBody } from '../models';
/**
 * GoalsApi - axios parameter creator
 */
export const GoalsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 创建目标
         * @param {GoalCreateGoalRequest} request 目标参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalCreate: async (request: GoalCreateGoalRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('goalCreate', 'request', request)
            const localVarPath = `/api/goals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取目标详情
         * @param {number} id 目标ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('goalGet', 'id', id)
            const localVarPath = `/api/goals/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取目标列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalsList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/goals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GoalsApi - functional programming interface
 */
export const GoalsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GoalsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 创建目标
         * @param {GoalCreateGoalRequest} request 目标参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goalCreate(request: GoalCreateGoalRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GoalGoalResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goalCreate(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GoalsApi.goalCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取目标详情
         * @param {number} id 目标ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goalGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GoalGoalResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goalGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GoalsApi.goalGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取目标列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goalsList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GoalGoalListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goalsList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GoalsApi.goalsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GoalsApi - factory interface
 */
export const GoalsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GoalsApiFp(configuration)
    return {
        /**
         * 
         * @summary 创建目标
         * @param {GoalsApiGoalCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalCreate(requestParameters: GoalsApiGoalCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<GoalGoalResponse> {
            return localVarFp.goalCreate(requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取目标详情
         * @param {GoalsApiGoalGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalGet(requestParameters: GoalsApiGoalGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<GoalGoalResponse> {
            return localVarFp.goalGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取目标列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalsList(options?: RawAxiosRequestConfig): AxiosPromise<GoalGoalListResponse> {
            return localVarFp.goalsList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for goalCreate operation in GoalsApi.
 */
export interface GoalsApiGoalCreateRequest {
    /**
     * 目标参数
     */
    readonly request: GoalCreateGoalRequest
}

/**
 * Request parameters for goalGet operation in GoalsApi.
 */
export interface GoalsApiGoalGetRequest {
    /**
     * 目标ID
     */
    readonly id: number
}

/**
 * GoalsApi - object-oriented interface
 */
export class GoalsApi extends BaseAPI {
    /**
     * 
     * @summary 创建目标
     * @param {GoalsApiGoalCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public goalCreate(requestParameters: GoalsApiGoalCreateRequest, options?: RawAxiosRequestConfig) {
        return GoalsApiFp(this.configuration).goalCreate(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取目标详情
     * @param {GoalsApiGoalGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public goalGet(requestParameters: GoalsApiGoalGetRequest, options?: RawAxiosRequestConfig) {
        return GoalsApiFp(this.configuration).goalGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取目标列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public goalsList(options?: RawAxiosRequestConfig) {
        return GoalsApiFp(this.configuration).goalsList(options).then((request) => request(this.axios, this.basePath));
    }
}

