/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MenuCreateMenuRequest } from '../models';
// @ts-ignore
import type { MenuMenuListResponse } from '../models';
// @ts-ignore
import type { MenuMenuResponse } from '../models';
// @ts-ignore
import type { MenuUpdateMenuRequest } from '../models';
// @ts-ignore
import type { ResponseBody } from '../models';
// @ts-ignore
import type { ResponseErrorBody } from '../models';
/**
 * MenusApi - axios parameter creator
 */
export const MenusApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 新增菜单
         * @param {MenuCreateMenuRequest} request 菜单参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenuCreate: async (request: MenuCreateMenuRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('adminMenuCreate', 'request', request)
            const localVarPath = `/api/admin/menus`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除菜单
         * @param {number} id 菜单ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenuDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminMenuDelete', 'id', id)
            const localVarPath = `/api/admin/menus/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取菜单详情
         * @param {number} id 菜单ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenuGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminMenuGet', 'id', id)
            const localVarPath = `/api/admin/menus/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新菜单
         * @param {number} id 菜单ID
         * @param {MenuUpdateMenuRequest} request 菜单参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenuUpdate: async (id: number, request: MenuUpdateMenuRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminMenuUpdate', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('adminMenuUpdate', 'request', request)
            const localVarPath = `/api/admin/menus/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取菜单列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenusList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/menus`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MenusApi - functional programming interface
 */
export const MenusApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MenusApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 新增菜单
         * @param {MenuCreateMenuRequest} request 菜单参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminMenuCreate(request: MenuCreateMenuRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuMenuResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminMenuCreate(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenusApi.adminMenuCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 删除菜单
         * @param {number} id 菜单ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminMenuDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminMenuDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenusApi.adminMenuDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取菜单详情
         * @param {number} id 菜单ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminMenuGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuMenuResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminMenuGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenusApi.adminMenuGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新菜单
         * @param {number} id 菜单ID
         * @param {MenuUpdateMenuRequest} request 菜单参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminMenuUpdate(id: number, request: MenuUpdateMenuRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuMenuResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminMenuUpdate(id, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenusApi.adminMenuUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取菜单列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminMenusList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MenuMenuListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminMenusList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MenusApi.adminMenusList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MenusApi - factory interface
 */
export const MenusApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MenusApiFp(configuration)
    return {
        /**
         * 
         * @summary 新增菜单
         * @param {MenusApiAdminMenuCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenuCreate(requestParameters: MenusApiAdminMenuCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuMenuResponse> {
            return localVarFp.adminMenuCreate(requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除菜单
         * @param {MenusApiAdminMenuDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenuDelete(requestParameters: MenusApiAdminMenuDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseBody> {
            return localVarFp.adminMenuDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取菜单详情
         * @param {MenusApiAdminMenuGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenuGet(requestParameters: MenusApiAdminMenuGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuMenuResponse> {
            return localVarFp.adminMenuGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新菜单
         * @param {MenusApiAdminMenuUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenuUpdate(requestParameters: MenusApiAdminMenuUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MenuMenuResponse> {
            return localVarFp.adminMenuUpdate(requestParameters.id, requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取菜单列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminMenusList(options?: RawAxiosRequestConfig): AxiosPromise<MenuMenuListResponse> {
            return localVarFp.adminMenusList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for adminMenuCreate operation in MenusApi.
 */
export interface MenusApiAdminMenuCreateRequest {
    /**
     * 菜单参数
     */
    readonly request: MenuCreateMenuRequest
}

/**
 * Request parameters for adminMenuDelete operation in MenusApi.
 */
export interface MenusApiAdminMenuDeleteRequest {
    /**
     * 菜单ID
     */
    readonly id: number
}

/**
 * Request parameters for adminMenuGet operation in MenusApi.
 */
export interface MenusApiAdminMenuGetRequest {
    /**
     * 菜单ID
     */
    readonly id: number
}

/**
 * Request parameters for adminMenuUpdate operation in MenusApi.
 */
export interface MenusApiAdminMenuUpdateRequest {
    /**
     * 菜单ID
     */
    readonly id: number

    /**
     * 菜单参数
     */
    readonly request: MenuUpdateMenuRequest
}

/**
 * MenusApi - object-oriented interface
 */
export class MenusApi extends BaseAPI {
    /**
     * 
     * @summary 新增菜单
     * @param {MenusApiAdminMenuCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminMenuCreate(requestParameters: MenusApiAdminMenuCreateRequest, options?: RawAxiosRequestConfig) {
        return MenusApiFp(this.configuration).adminMenuCreate(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除菜单
     * @param {MenusApiAdminMenuDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminMenuDelete(requestParameters: MenusApiAdminMenuDeleteRequest, options?: RawAxiosRequestConfig) {
        return MenusApiFp(this.configuration).adminMenuDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取菜单详情
     * @param {MenusApiAdminMenuGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminMenuGet(requestParameters: MenusApiAdminMenuGetRequest, options?: RawAxiosRequestConfig) {
        return MenusApiFp(this.configuration).adminMenuGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新菜单
     * @param {MenusApiAdminMenuUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminMenuUpdate(requestParameters: MenusApiAdminMenuUpdateRequest, options?: RawAxiosRequestConfig) {
        return MenusApiFp(this.configuration).adminMenuUpdate(requestParameters.id, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取菜单列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminMenusList(options?: RawAxiosRequestConfig) {
        return MenusApiFp(this.configuration).adminMenusList(options).then((request) => request(this.axios, this.basePath));
    }
}

