/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PlanPlanResponse } from '../models';
// @ts-ignore
import type { ResponseErrorBody } from '../models';
/**
 * PlansApi - axios parameter creator
 */
export const PlansApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 生成目标计划
         * @param {number} id 目标ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalPlanGenerate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('goalPlanGenerate', 'id', id)
            const localVarPath = `/api/goals/{id}/generate-plan`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取目标计划
         * @param {number} id 目标ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalPlanGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('goalPlanGet', 'id', id)
            const localVarPath = `/api/goals/{id}/plan`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 重新生成目标计划
         * @param {number} id 目标ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalPlanRegenerate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('goalPlanRegenerate', 'id', id)
            const localVarPath = `/api/goals/{id}/regenerate-plan`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlansApi - functional programming interface
 */
export const PlansApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlansApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 生成目标计划
         * @param {number} id 目标ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goalPlanGenerate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlanPlanResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goalPlanGenerate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlansApi.goalPlanGenerate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取目标计划
         * @param {number} id 目标ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goalPlanGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlanPlanResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goalPlanGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlansApi.goalPlanGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 重新生成目标计划
         * @param {number} id 目标ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goalPlanRegenerate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlanPlanResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goalPlanRegenerate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlansApi.goalPlanRegenerate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PlansApi - factory interface
 */
export const PlansApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlansApiFp(configuration)
    return {
        /**
         * 
         * @summary 生成目标计划
         * @param {PlansApiGoalPlanGenerateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalPlanGenerate(requestParameters: PlansApiGoalPlanGenerateRequest, options?: RawAxiosRequestConfig): AxiosPromise<PlanPlanResponse> {
            return localVarFp.goalPlanGenerate(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取目标计划
         * @param {PlansApiGoalPlanGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalPlanGet(requestParameters: PlansApiGoalPlanGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<PlanPlanResponse> {
            return localVarFp.goalPlanGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 重新生成目标计划
         * @param {PlansApiGoalPlanRegenerateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goalPlanRegenerate(requestParameters: PlansApiGoalPlanRegenerateRequest, options?: RawAxiosRequestConfig): AxiosPromise<PlanPlanResponse> {
            return localVarFp.goalPlanRegenerate(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for goalPlanGenerate operation in PlansApi.
 */
export interface PlansApiGoalPlanGenerateRequest {
    /**
     * 目标ID
     */
    readonly id: number
}

/**
 * Request parameters for goalPlanGet operation in PlansApi.
 */
export interface PlansApiGoalPlanGetRequest {
    /**
     * 目标ID
     */
    readonly id: number
}

/**
 * Request parameters for goalPlanRegenerate operation in PlansApi.
 */
export interface PlansApiGoalPlanRegenerateRequest {
    /**
     * 目标ID
     */
    readonly id: number
}

/**
 * PlansApi - object-oriented interface
 */
export class PlansApi extends BaseAPI {
    /**
     * 
     * @summary 生成目标计划
     * @param {PlansApiGoalPlanGenerateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public goalPlanGenerate(requestParameters: PlansApiGoalPlanGenerateRequest, options?: RawAxiosRequestConfig) {
        return PlansApiFp(this.configuration).goalPlanGenerate(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取目标计划
     * @param {PlansApiGoalPlanGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public goalPlanGet(requestParameters: PlansApiGoalPlanGetRequest, options?: RawAxiosRequestConfig) {
        return PlansApiFp(this.configuration).goalPlanGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 重新生成目标计划
     * @param {PlansApiGoalPlanRegenerateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public goalPlanRegenerate(requestParameters: PlansApiGoalPlanRegenerateRequest, options?: RawAxiosRequestConfig) {
        return PlansApiFp(this.configuration).goalPlanRegenerate(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

