/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RbacCreatePermissionRequest } from '../models';
// @ts-ignore
import type { RbacPermissionListResponse } from '../models';
// @ts-ignore
import type { RbacPermissionResponse } from '../models';
// @ts-ignore
import type { RbacRoleListResponse } from '../models';
// @ts-ignore
import type { RbacRolePermissionIDsResponse } from '../models';
// @ts-ignore
import type { RbacUpdatePermissionRequest } from '../models';
// @ts-ignore
import type { RbacUpdateRolePermissionsRequest } from '../models';
// @ts-ignore
import type { ResponseBody } from '../models';
// @ts-ignore
import type { ResponseErrorBody } from '../models';
/**
 * RbacApi - axios parameter creator
 */
export const RbacApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 新增权限
         * @param {RbacCreatePermissionRequest} request 权限参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminPermissionCreate: async (request: RbacCreatePermissionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('adminPermissionCreate', 'request', request)
            const localVarPath = `/api/admin/permissions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除权限
         * @param {number} id 权限ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminPermissionDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminPermissionDelete', 'id', id)
            const localVarPath = `/api/admin/permissions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新权限
         * @param {number} id 权限ID
         * @param {RbacUpdatePermissionRequest} request 权限参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminPermissionUpdate: async (id: number, request: RbacUpdatePermissionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminPermissionUpdate', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('adminPermissionUpdate', 'request', request)
            const localVarPath = `/api/admin/permissions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取权限列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminPermissionsList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/permissions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取角色权限绑定
         * @param {number} id 角色ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRolePermissionsGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminRolePermissionsGet', 'id', id)
            const localVarPath = `/api/admin/roles/{id}/permissions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新角色权限绑定
         * @param {number} id 角色ID
         * @param {RbacUpdateRolePermissionsRequest} request 角色权限参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRolePermissionsUpdate: async (id: number, request: RbacUpdateRolePermissionsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminRolePermissionsUpdate', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('adminRolePermissionsUpdate', 'request', request)
            const localVarPath = `/api/admin/roles/{id}/permissions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取角色列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRolesList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RbacApi - functional programming interface
 */
export const RbacApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RbacApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 新增权限
         * @param {RbacCreatePermissionRequest} request 权限参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminPermissionCreate(request: RbacCreatePermissionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RbacPermissionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminPermissionCreate(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RbacApi.adminPermissionCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 删除权限
         * @param {number} id 权限ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminPermissionDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminPermissionDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RbacApi.adminPermissionDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新权限
         * @param {number} id 权限ID
         * @param {RbacUpdatePermissionRequest} request 权限参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminPermissionUpdate(id: number, request: RbacUpdatePermissionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RbacPermissionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminPermissionUpdate(id, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RbacApi.adminPermissionUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取权限列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminPermissionsList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RbacPermissionListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminPermissionsList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RbacApi.adminPermissionsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取角色权限绑定
         * @param {number} id 角色ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminRolePermissionsGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RbacRolePermissionIDsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminRolePermissionsGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RbacApi.adminRolePermissionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新角色权限绑定
         * @param {number} id 角色ID
         * @param {RbacUpdateRolePermissionsRequest} request 角色权限参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminRolePermissionsUpdate(id: number, request: RbacUpdateRolePermissionsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RbacRolePermissionIDsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminRolePermissionsUpdate(id, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RbacApi.adminRolePermissionsUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取角色列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminRolesList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RbacRoleListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminRolesList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RbacApi.adminRolesList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RbacApi - factory interface
 */
export const RbacApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RbacApiFp(configuration)
    return {
        /**
         * 
         * @summary 新增权限
         * @param {RbacApiAdminPermissionCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminPermissionCreate(requestParameters: RbacApiAdminPermissionCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RbacPermissionResponse> {
            return localVarFp.adminPermissionCreate(requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除权限
         * @param {RbacApiAdminPermissionDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminPermissionDelete(requestParameters: RbacApiAdminPermissionDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseBody> {
            return localVarFp.adminPermissionDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新权限
         * @param {RbacApiAdminPermissionUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminPermissionUpdate(requestParameters: RbacApiAdminPermissionUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RbacPermissionResponse> {
            return localVarFp.adminPermissionUpdate(requestParameters.id, requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取权限列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminPermissionsList(options?: RawAxiosRequestConfig): AxiosPromise<RbacPermissionListResponse> {
            return localVarFp.adminPermissionsList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取角色权限绑定
         * @param {RbacApiAdminRolePermissionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRolePermissionsGet(requestParameters: RbacApiAdminRolePermissionsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<RbacRolePermissionIDsResponse> {
            return localVarFp.adminRolePermissionsGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新角色权限绑定
         * @param {RbacApiAdminRolePermissionsUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRolePermissionsUpdate(requestParameters: RbacApiAdminRolePermissionsUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RbacRolePermissionIDsResponse> {
            return localVarFp.adminRolePermissionsUpdate(requestParameters.id, requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取角色列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminRolesList(options?: RawAxiosRequestConfig): AxiosPromise<RbacRoleListResponse> {
            return localVarFp.adminRolesList(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for adminPermissionCreate operation in RbacApi.
 */
export interface RbacApiAdminPermissionCreateRequest {
    /**
     * 权限参数
     */
    readonly request: RbacCreatePermissionRequest
}

/**
 * Request parameters for adminPermissionDelete operation in RbacApi.
 */
export interface RbacApiAdminPermissionDeleteRequest {
    /**
     * 权限ID
     */
    readonly id: number
}

/**
 * Request parameters for adminPermissionUpdate operation in RbacApi.
 */
export interface RbacApiAdminPermissionUpdateRequest {
    /**
     * 权限ID
     */
    readonly id: number

    /**
     * 权限参数
     */
    readonly request: RbacUpdatePermissionRequest
}

/**
 * Request parameters for adminRolePermissionsGet operation in RbacApi.
 */
export interface RbacApiAdminRolePermissionsGetRequest {
    /**
     * 角色ID
     */
    readonly id: number
}

/**
 * Request parameters for adminRolePermissionsUpdate operation in RbacApi.
 */
export interface RbacApiAdminRolePermissionsUpdateRequest {
    /**
     * 角色ID
     */
    readonly id: number

    /**
     * 角色权限参数
     */
    readonly request: RbacUpdateRolePermissionsRequest
}

/**
 * RbacApi - object-oriented interface
 */
export class RbacApi extends BaseAPI {
    /**
     * 
     * @summary 新增权限
     * @param {RbacApiAdminPermissionCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminPermissionCreate(requestParameters: RbacApiAdminPermissionCreateRequest, options?: RawAxiosRequestConfig) {
        return RbacApiFp(this.configuration).adminPermissionCreate(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除权限
     * @param {RbacApiAdminPermissionDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminPermissionDelete(requestParameters: RbacApiAdminPermissionDeleteRequest, options?: RawAxiosRequestConfig) {
        return RbacApiFp(this.configuration).adminPermissionDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新权限
     * @param {RbacApiAdminPermissionUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminPermissionUpdate(requestParameters: RbacApiAdminPermissionUpdateRequest, options?: RawAxiosRequestConfig) {
        return RbacApiFp(this.configuration).adminPermissionUpdate(requestParameters.id, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取权限列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminPermissionsList(options?: RawAxiosRequestConfig) {
        return RbacApiFp(this.configuration).adminPermissionsList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取角色权限绑定
     * @param {RbacApiAdminRolePermissionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminRolePermissionsGet(requestParameters: RbacApiAdminRolePermissionsGetRequest, options?: RawAxiosRequestConfig) {
        return RbacApiFp(this.configuration).adminRolePermissionsGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新角色权限绑定
     * @param {RbacApiAdminRolePermissionsUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminRolePermissionsUpdate(requestParameters: RbacApiAdminRolePermissionsUpdateRequest, options?: RawAxiosRequestConfig) {
        return RbacApiFp(this.configuration).adminRolePermissionsUpdate(requestParameters.id, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取角色列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminRolesList(options?: RawAxiosRequestConfig) {
        return RbacApiFp(this.configuration).adminRolesList(options).then((request) => request(this.axios, this.basePath));
    }
}

