/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ResponseErrorBody } from '../models';
// @ts-ignore
import type { TaskCreateTaskRequest } from '../models';
// @ts-ignore
import type { TaskDeleteTaskResponse } from '../models';
// @ts-ignore
import type { TaskTaskListResponse } from '../models';
// @ts-ignore
import type { TaskTaskResponse } from '../models';
// @ts-ignore
import type { TaskUpdateTaskRequest } from '../models';
// @ts-ignore
import type { TaskUpdateTaskStatusRequest } from '../models';
/**
 * TasksApi - axios parameter creator
 */
export const TasksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 新增任务
         * @param {TaskCreateTaskRequest} request 任务信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskCreate: async (request: TaskCreateTaskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('taskCreate', 'request', request)
            const localVarPath = `/api/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除任务
         * @param {number} id 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('taskDelete', 'id', id)
            const localVarPath = `/api/tasks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取任务详情
         * @param {number} id 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('taskGet', 'id', id)
            const localVarPath = `/api/tasks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 编辑任务
         * @param {number} id 任务ID
         * @param {TaskUpdateTaskRequest} request 任务信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskUpdate: async (id: number, request: TaskUpdateTaskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('taskUpdate', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('taskUpdate', 'request', request)
            const localVarPath = `/api/tasks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新任务状态
         * @param {number} id 任务ID
         * @param {TaskUpdateTaskStatusRequest} request 任务状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskUpdateStatus: async (id: number, request: TaskUpdateTaskStatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('taskUpdateStatus', 'id', id)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('taskUpdateStatus', 'request', request)
            const localVarPath = `/api/tasks/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取任务列表
         * @param {string} [status] 任务状态
         * @param {number} [goalId] 目标ID
         * @param {number} [phaseId] 阶段ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksList: async (status?: string, goalId?: number, phaseId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (goalId !== undefined) {
                localVarQueryParameter['goal_id'] = goalId;
            }

            if (phaseId !== undefined) {
                localVarQueryParameter['phase_id'] = phaseId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TasksApi - functional programming interface
 */
export const TasksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TasksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 新增任务
         * @param {TaskCreateTaskRequest} request 任务信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async taskCreate(request: TaskCreateTaskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskTaskResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.taskCreate(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.taskCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 删除任务
         * @param {number} id 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async taskDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskDeleteTaskResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.taskDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.taskDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取任务详情
         * @param {number} id 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async taskGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskTaskResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.taskGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.taskGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 编辑任务
         * @param {number} id 任务ID
         * @param {TaskUpdateTaskRequest} request 任务信息
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async taskUpdate(id: number, request: TaskUpdateTaskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskTaskResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.taskUpdate(id, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.taskUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新任务状态
         * @param {number} id 任务ID
         * @param {TaskUpdateTaskStatusRequest} request 任务状态
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async taskUpdateStatus(id: number, request: TaskUpdateTaskStatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskTaskResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.taskUpdateStatus(id, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.taskUpdateStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取任务列表
         * @param {string} [status] 任务状态
         * @param {number} [goalId] 目标ID
         * @param {number} [phaseId] 阶段ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tasksList(status?: string, goalId?: number, phaseId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskTaskListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tasksList(status, goalId, phaseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TasksApi.tasksList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TasksApi - factory interface
 */
export const TasksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TasksApiFp(configuration)
    return {
        /**
         * 
         * @summary 新增任务
         * @param {TasksApiTaskCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskCreate(requestParameters: TasksApiTaskCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaskTaskResponse> {
            return localVarFp.taskCreate(requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除任务
         * @param {TasksApiTaskDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskDelete(requestParameters: TasksApiTaskDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaskDeleteTaskResponse> {
            return localVarFp.taskDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取任务详情
         * @param {TasksApiTaskGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskGet(requestParameters: TasksApiTaskGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaskTaskResponse> {
            return localVarFp.taskGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 编辑任务
         * @param {TasksApiTaskUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskUpdate(requestParameters: TasksApiTaskUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaskTaskResponse> {
            return localVarFp.taskUpdate(requestParameters.id, requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新任务状态
         * @param {TasksApiTaskUpdateStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskUpdateStatus(requestParameters: TasksApiTaskUpdateStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaskTaskResponse> {
            return localVarFp.taskUpdateStatus(requestParameters.id, requestParameters.request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取任务列表
         * @param {TasksApiTasksListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasksList(requestParameters: TasksApiTasksListRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<TaskTaskListResponse> {
            return localVarFp.tasksList(requestParameters.status, requestParameters.goalId, requestParameters.phaseId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for taskCreate operation in TasksApi.
 */
export interface TasksApiTaskCreateRequest {
    /**
     * 任务信息
     */
    readonly request: TaskCreateTaskRequest
}

/**
 * Request parameters for taskDelete operation in TasksApi.
 */
export interface TasksApiTaskDeleteRequest {
    /**
     * 任务ID
     */
    readonly id: number
}

/**
 * Request parameters for taskGet operation in TasksApi.
 */
export interface TasksApiTaskGetRequest {
    /**
     * 任务ID
     */
    readonly id: number
}

/**
 * Request parameters for taskUpdate operation in TasksApi.
 */
export interface TasksApiTaskUpdateRequest {
    /**
     * 任务ID
     */
    readonly id: number

    /**
     * 任务信息
     */
    readonly request: TaskUpdateTaskRequest
}

/**
 * Request parameters for taskUpdateStatus operation in TasksApi.
 */
export interface TasksApiTaskUpdateStatusRequest {
    /**
     * 任务ID
     */
    readonly id: number

    /**
     * 任务状态
     */
    readonly request: TaskUpdateTaskStatusRequest
}

/**
 * Request parameters for tasksList operation in TasksApi.
 */
export interface TasksApiTasksListRequest {
    /**
     * 任务状态
     */
    readonly status?: string

    /**
     * 目标ID
     */
    readonly goalId?: number

    /**
     * 阶段ID
     */
    readonly phaseId?: number
}

/**
 * TasksApi - object-oriented interface
 */
export class TasksApi extends BaseAPI {
    /**
     * 
     * @summary 新增任务
     * @param {TasksApiTaskCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public taskCreate(requestParameters: TasksApiTaskCreateRequest, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).taskCreate(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除任务
     * @param {TasksApiTaskDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public taskDelete(requestParameters: TasksApiTaskDeleteRequest, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).taskDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取任务详情
     * @param {TasksApiTaskGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public taskGet(requestParameters: TasksApiTaskGetRequest, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).taskGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 编辑任务
     * @param {TasksApiTaskUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public taskUpdate(requestParameters: TasksApiTaskUpdateRequest, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).taskUpdate(requestParameters.id, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新任务状态
     * @param {TasksApiTaskUpdateStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public taskUpdateStatus(requestParameters: TasksApiTaskUpdateStatusRequest, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).taskUpdateStatus(requestParameters.id, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取任务列表
     * @param {TasksApiTasksListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public tasksList(requestParameters: TasksApiTasksListRequest = {}, options?: RawAxiosRequestConfig) {
        return TasksApiFp(this.configuration).tasksList(requestParameters.status, requestParameters.goalId, requestParameters.phaseId, options).then((request) => request(this.axios, this.basePath));
    }
}

