/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AuthMenu {
    'children'?: Array<AuthMenu>;
    'component'?: string;
    'hidden'?: boolean;
    'icon'?: string;
    'id'?: number;
    'name'?: string;
    'parent_id'?: number;
    'path'?: string;
    'permission_code'?: string;
    'sort_order'?: number;
}

