/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AuthLoginData {
    /**
     * Nickname 昵称
     */
    'nickname'?: string;
    /**
     * Token 登录令牌
     */
    'token'?: string;
    /**
     * UserID 用户ID
     */
    'user_id'?: number;
    /**
     * Username 用户名
     */
    'username'?: string;
}

