/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GoalCreateGoalRequest {
    /**
     * Category 目标分类
     */
    'category'?: string;
    /**
     * Description 目标描述
     */
    'description'?: string;
    /**
     * TargetDeadline 截止时间
     */
    'target_deadline'?: string;
    /**
     * Title 目标标题
     */
    'title'?: string;
}

