/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GoalGoalStatus } from './goal-goal-status';

export interface GoalUpdateGoalStatusRequest {
    /**
     * Status 目标状态
     */
    'status'?: GoalGoalStatus;
}



