/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




/**
 * 目标状态
 * - draft: 未执行
 * - active: 执行中
 * - completed: 已完成
 * - archived: 已归档
 */
export enum GoalGoalStatus {
    GoalStatusDraft = 'draft',
    GoalStatusActive = 'active',
    GoalStatusCompleted = 'completed',
    GoalStatusArchived = 'archived'
}



