/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GoalGoal } from './goal-goal';

export interface GoalGoalListData {
    /**
     * List 目标列表
     */
    'list'?: Array<GoalGoal>;
    /**
     * Total 总数
     */
    'total'?: number;
}

