/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PhaseNextStepSuggestion {
    /**
     * Checklist 执行清单
     */
    'checklist'?: Array<string>;
    /**
     * NextAction 建议执行动作
     */
    'next_action'?: string;
    /**
     * Reason 建议原因
     */
    'reason'?: string;
    /**
     * Risk 主要风险
     */
    'risk'?: string;
    /**
     * Summary 执行建议摘要
     */
    'summary'?: string;
}

