/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PhasePhase {
    /**
     * CreatedAt 创建时间
     */
    'created_at'?: string;
    /**
     * Description 阶段描述
     */
    'description'?: string;
    /**
     * GoalID 所属目标ID
     */
    'goal_id'?: number;
    /**
     * ID 阶段ID
     */
    'id'?: number;
    /**
     * PlanID 所属计划ID
     */
    'plan_id'?: number;
    /**
     * SortOrder 阶段顺序
     */
    'sort_order'?: number;
    /**
     * Title 阶段标题
     */
    'title'?: string;
    /**
     * UpdatedAt 更新时间
     */
    'updated_at'?: string;
}

