/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PhaseUpdatePhaseRequest {
    /**
     * Description 阶段描述
     */
    'description'?: string;
    /**
     * SortOrder 阶段顺序
     */
    'sort_order'?: number;
    /**
     * Title 阶段标题
     */
    'title'?: string;
}

