/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlanPhase } from './plan-phase';

export interface PlanPlan {
    /**
     * CreatedAt 创建时间
     */
    'created_at'?: string;
    /**
     * GoalID 目标ID
     */
    'goal_id'?: number;
    /**
     * ID 计划ID
     */
    'id'?: number;
    /**
     * Overview 计划概述
     */
    'overview'?: string;
    /**
     * Phases 阶段列表
     */
    'phases'?: Array<PlanPhase>;
    /**
     * Title 计划标题
     */
    'title'?: string;
    /**
     * UpdatedAt 更新时间
     */
    'updated_at'?: string;
    /**
     * UserID 用户ID
     */
    'user_id'?: number;
}

