/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PlanUpdatePlanRequest {
    /**
     * Overview 计划概述
     */
    'overview'?: string;
    /**
     * Title 计划标题
     */
    'title'?: string;
}

