/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RbacPermission {
    /**
     * Code 权限编码
     */
    'code'?: string;
    /**
     * CreatedAt 创建时间
     */
    'created_at'?: string;
    /**
     * ID 权限ID
     */
    'id'?: number;
    /**
     * Name 权限名称
     */
    'name'?: string;
    /**
     * UpdatedAt 更新时间
     */
    'updated_at'?: string;
}

