/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RbacRole {
    /**
     * Code 角色编码
     */
    'code'?: string;
    /**
     * CreatedAt 创建时间
     */
    'created_at'?: string;
    /**
     * ID 角色ID
     */
    'id'?: number;
    /**
     * Name 角色名称
     */
    'name'?: string;
    /**
     * PermissionIDs 当前角色绑定的权限ID列表
     */
    'permission_ids'?: Array<number>;
    /**
     * UpdatedAt 更新时间
     */
    'updated_at'?: string;
}

