/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskTaskStatus } from './task-task-status';

export interface TaskUpdateTaskStatusRequest {
    /**
     * Status 任务状态：todo 待开始，in_progress 进行中，done 已完成
     */
    'status'?: TaskTaskStatus;
}



