/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskTaskPriority } from './task-task-priority';
// May contain unused imports in some cases
// @ts-ignore
import type { TaskTaskStatus } from './task-task-status';

export interface TaskTask {
    /**
     * CreatedAt 创建时间
     */
    'created_at'?: string;
    /**
     * Deadline 任务截止时间
     */
    'deadline'?: string;
    /**
     * Deliverables 交付物
     */
    'deliverables'?: string;
    /**
     * Description 任务描述
     */
    'description'?: string;
    /**
     * EstimatedDays 预估天数
     */
    'estimated_days'?: number;
    /**
     * GoalID 所属目标ID
     */
    'goal_id'?: number;
    /**
     * GoalTitle 目标标题
     */
    'goal_title'?: string;
    /**
     * ID 任务ID
     */
    'id'?: number;
    /**
     * PhaseID 所属阶段ID
     */
    'phase_id'?: number;
    /**
     * PhaseTitle 阶段标题
     */
    'phase_title'?: string;
    /**
     * PlanID 所属计划ID
     */
    'plan_id'?: number;
    /**
     * Priority 任务优先级
     */
    'priority'?: TaskTaskPriority;
    /**
     * SortOrder 任务顺序
     */
    'sort_order'?: number;
    /**
     * Status 任务状态
     */
    'status'?: TaskTaskStatus;
    /**
     * Title 任务标题
     */
    'title'?: string;
    /**
     * UpdatedAt 更新时间
     */
    'updated_at'?: string;
}



