/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskTaskPriority } from './task-task-priority';

export interface TaskCreateTaskRequest {
    /**
     * Deadline 任务截止时间，使用 RFC3339 格式
     */
    'deadline'?: string;
    /**
     * Deliverables 交付物
     */
    'deliverables'?: string;
    /**
     * Description 任务描述
     */
    'description'?: string;
    /**
     * EstimatedDays 预估天数
     */
    'estimated_days'?: number;
    /**
     * PhaseID 所属阶段ID
     */
    'phase_id'?: number;
    /**
     * Priority 任务优先级：high 高，medium 中，low 低
     */
    'priority'?: TaskTaskPriority;
    /**
     * SortOrder 任务顺序
     */
    'sort_order'?: number;
    /**
     * Title 任务标题
     */
    'title'?: string;
}



