/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskTask } from './task-task';

export interface TaskTaskListData {
    /**
     * List 任务列表
     */
    'list'?: Array<TaskTask>;
    /**
     * Page 当前页
     */
    'page'?: number;
    /**
     * PageSize 每页条数
     */
    'page_size'?: number;
    /**
     * Total 总数量
     */
    'total'?: number;
}

