/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserRole {
    /**
     * Code 角色编码
     */
    'code'?: string;
    /**
     * ID 角色ID
     */
    'id'?: number;
    /**
     * Name 角色名称
     */
    'name'?: string;
}

