/* tslint:disable */
/* eslint-disable */
/**
 * Goal Planner Backend API
 * Goal Planner 后端接口文档
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserRole } from './user-role';

export interface UserUser {
    /**
     * CreatedAt 创建时间
     */
    'created_at'?: string;
    /**
     * Email 邮箱
     */
    'email'?: string;
    /**
     * ID 用户ID
     */
    'id'?: number;
    /**
     * Nickname 昵称
     */
    'nickname'?: string;
    /**
     * RoleIDs 已绑定角色ID
     */
    'role_ids'?: Array<number>;
    /**
     * Roles 已绑定角色列表
     */
    'roles'?: Array<UserRole>;
    /**
     * Status 用户状态
     */
    'status'?: string;
    /**
     * UpdatedAt 更新时间
     */
    'updated_at'?: string;
    /**
     * Username 用户名
     */
    'username'?: string;
}

